site_name: Tianshu Huang
nav:
  - About: index.md
  - Research: research.md
  - Open Source: open-source.md
  # - Photography: photography.md

theme:
  name: material
  custom_dir: overrides
  favicon: assets/favicon.png
  icon:
    logo: octicons/person-16
    annotation: material/arrow-right-circle
  features:
    - navigation.instant
    - navigation.expand
    - navigation.tabs
  palette:
    primary: black
    accent: indigo

watch:
  - docs
  - data

extra_css:
  - stylesheets/extra.css

plugins:
- publications:
    index: data/research.yaml
- collaborators:
    index: data/people.yaml
- photos:
    index: data/photos.yaml
- glightbox:
    manual: true

markdown_extensions:
  - attr_list
  - def_list
  - md_in_html
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: >
  &copy; 2025 Tianshu Huang
